### ISSUE TITLE
Offset mismatch

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/javascript-driver#33]
https://github.com/facebook/react/blob/master/fixtures/unstable-async/suspense/src/api/data.js

"trueadm" vs. "ueadm: " according to the offsets

https://github.com/facebook/react/blob/master/fixtures/attribute-behavior/src/App.js

"width" vs. "idth}" according to the offsets

**Comment by dennwc** [comment]
Is this from v2 driver?

**Comment by vmarkovtsev** [comment]
It is v1

**Comment by dennwc** [comment]
You can test against `v2.1.1` version (using v1 API). This bug should be fixed there.

**Comment by vmarkovtsev** [comment]
@warenlg can you please check this tomorrow

**Comment by warenlg** [comment]
Locally with `v2.1.1` of the js-driver,I can not reproduce this offset mismatch
