### ISSUE TITLE
Parsing fails on valid JS: string

### ISSUE THREAD

**Issue by bzz** [bblfsh/javascript-driver#62]
Parsing `string.js` file with content

```js
var escSlash = '\0SLASH'+Math.random()+'\0';
var escOpen = '\0OPEN'+Math.random()+'\0';
var escClose = '\0CLOSE'+Math.random()+'\0';
var escComma = '\0COMMA'+Math.random()+'\0';
var escPeriod = '\0PERIOD'+Math.random()+'\0';
```

results in 

```
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0SLASH')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0OPEN')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0CLOSE')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0COMMA')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0')
 check: key "value": invalid syntax
 check: key "value": invalid syntax ('\0PERIOD')
```

Found though #54 

## Steps to reproduce
```
$ bblfsh-cli string.js
```

**Comment by bzz** [comment]
The issue comes from `strconv.go#unquoteSingle` here is a simple test case to reproduce

```go
func TestUnquoteSingle(T *testing.T) {
	s, err := unquoteSingle(`'\0'`)
	require.NoError(T, err)
}
```

From original PR discussion https://github.com/bblfsh/javascript-driver/pull/50#issuecomment-452670808

>As for strconv.go, I don't think it requires extensive test coverage since it's copied from the Go stdlib, which already ensures that the code is correct. But we can add a few small test cases to detect regressions.

**Comment by bzz** [comment]
The cause is an error from `strconv.UnquoteChar(`'\0'`, '\'')`

**Comment by bzz** [comment]
Seems to be related to the difference how `\0` is treated in 2 languages:
 - in ES5 `\0` is treated the same as a single byte escape sequence (even if it is not, http://es5.github.io/x7.html#x7.8.4) equivalent to hex `\x00` or octal `\000` (deprecated in `strict` mode) and is meant to represent `U+0000`
 - in Golang it does not get any special treatment

A proposed solution includes converting `\0` to the` \x00` in Semantic mode.

Current implementation of Op `singleQuote` is supposed to behave like `strconv.Unquote`, but
 - ✅`strconv.Unquote("\\0")`  -> `syntax error`
 - ✅`unquoteSingle("'\\0'")`    -> `syntax error`
 - ✅`strconv.Unquote("\x00")` -> `U+000`
 - 🚫`unquoteSingle("'\x00'")`  -> `syntax error`

**Comment by creachadair** [comment]
> A proposed solution includes converting `\0` to the` \x00` on Golang side in the Semantic mode.

That seems reasonable. The details of how we handle unquoting are private to the implementation, so if we have to do some patch-work it shouldn't break anything fundamental. 

Unfortunately there are a lot of subtle variations in (un)escaping rules for string literals, and the desire to lean on Go's implementation is understandable but doesn't always line up correctly with other languages. 🙍🏻‍♀️
