### ISSUE TITLE
Operator Role missing position information

### ISSUE THREAD

**Issue by zurk** [bblfsh/javascript-driver#65]
Run:
```bash
echo "var a = 0 + 1;" > o.js
docker run -d --rm --name style_analyzer_bblfshd_new --privileged -p 9432:9432 bblfsh/bblfshd\:v2.11.0 --log-level DEBUG
docker exec style_analyzer_bblfshd_new bblfshctl driver install javascript docker://bblfsh/javascript-driver:v2.6.0
docker cp o.js style_analyzer_bblfshd_new:o.js
docker exec -it style_analyzer_bblfshd_new bblfshctl parse o.js
```
You get next UAST: https://gist.github.com/zurk/b594c7642a1bdfeca334ab27a2394426
And operator tokens are missing their positions:
```
.  .  .  .  .  .  .  .  .  .  0: Operator {
.  .  .  .  .  .  .  .  .  .  .  Roles: Arithmetic,Add,Expression,Operator,Binary
.  .  .  .  .  .  .  .  .  .  .  TOKEN "+"
.  .  .  .  .  .  .  .  .  .  .  Properties: {
.  .  .  .  .  .  .  .  .  .  .  .  internalRole: operator
.  .  .  .  .  .  .  .  .  .  .  }
.  .  .  .  .  .  .  .  .  .  }
```

And for driver v.1.2.0 I do not see this node. So I think it was added inside bblfsh, but without position information. It should be easy to include positions because you have positions for the right and left part of the expression.

**Comment by bzz** [comment]
Removing the assignment as it's used to communicated that something "has been take" and is kind-of-WIP but I'm not looking into this yet until the initial scope of https://github.com/bblfsh/javascript-driver/milestone/1 is finished.

Will get back to this ASAP right after though.

**Comment by bzz** [comment]
Indeed, some drivers do not have position at the operator node of the binary expression in annotated UAST: js, java. Others do: cpp.

In some language native ASTs, there is no position information for a node representing such operation e.g `InfixExpression` in `java` does not have it.

In others, like `js` and `cpp`, there is a position in native AST. 

Thus I'll suggest to treat this issue like a bug in js driver (native AST has position, UAST does not).

But we also would need to have a broader discussion \w @creachadair and @dennwc on user expectations and a way of dealing with the same question e.g for a java-driver and alike, where native AST does _not_ have this position, => UAST does not as well.

**Comment by bzz** [comment]
After digging deeper, I could not find a driver that have a position information for `'@type': "uast:Operator"`
 - [js](https://github.com/bblfsh/javascript-driver/blob/6739710f2fe3ba93e2a7491b794908b8440a5772/fixtures/assignment-expression.js.sem.uast#L75)
 - [go](https://github.com/bblfsh/go-driver/blob/dd977093c48285eb94187e817f3960d061552d35/fixtures/augmented_assign.go.sem.uast#L110)
 - [ruby](https://github.com/bblfsh/ruby-driver/blob/a144f125ffa383935d26bda67ba32c6233e5a022/fixtures/augassign.rb.uast#L33)
 - [java](https://github.com/bblfsh/java-driver/blob/5596879ac82173c859740eefdd9367dd26522ca3/fixtures/operators.java.sem.uast#L191)

So I would assume it's `wontfix` for JS, but would ask @dennwc to verify that.

**Comment by dennwc** [comment]
Correct, I think it's "won't fix" for now. We need to change the tokenizer for this to work.

**Comment by zurk** [comment]
Ok, it is not critical, we have a workaround.
